name: Pipelines

on: [ push ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    name: Analysis
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          pip install mypy
      - name: mypy
        run: make analysis
  tests:
    runs-on: ubuntu-latest
    name: Tests
    needs: analysis
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          pip install pydot coverage pytest
      - name: Launch tests
        run: |  
          make test
          coverage report -m