name: Pipelines

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Analysis
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        sudo apt-get install graphviz
        pip install mypy
        pip install pydot
    - name: mypy
      run: |
        mypy classes/**/*.py
    tests:
      runs-on: ubuntu-latest
      name: Analysis
      steps:
        - uses: actions/checkout@v1
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install Dependencies
          run: |
            sudo apt-get install graphviz
            pip install mypy
            pip install pydot
        - name: mypy
          run: |
            python3.7 -m unittest tests