name: Pipelines

on: [ push ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    runs-on: ubuntu-latest
    name: Analysis
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          pip install mypy
      - name: mypy
        run: make analysis
  tests:
    runs-on: ubuntu-latest
    name: Tests
    needs: analysis
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          pip install pydot coverage pytest
      - name: Launch tests
        run: |
          make test
          coverage report -m --data-file=cache/coverage/data
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: execute
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf python-translation
            git clone git@github.com:MartinLenaerts/engineering-project.git python-translation
            cd python-translation
            git checkout main
