name: Pipelines

on: [ push ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    name: Analysis
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          pip install mypy
      - name: mypy
        run: |
          mypy **/*.py
  tests:
    runs-on: ubuntu-latest
    name: Tests
    needs: analysis
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          pip install pydot coverage dotenv
      - name: Launch tests
        run: |
          coverage run -m unittest discover
          coverage report -m